# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/imageProcessing/imageProcessing.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessing || ORIG_REF_NAME==imageProcessing} -quiet] -quiet

# IP: bd/imageProcessing/ip/imageProcessing_processing_system7_0_0/imageProcessing_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessing_processing_system7_0_0 || ORIG_REF_NAME==imageProcessing_processing_system7_0_0} -quiet] -quiet

# IP: bd/imageProcessing/ip/imageProcessing_imageProcess_0_0/imageProcessing_imageProcess_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessing_imageProcess_0_0 || ORIG_REF_NAME==imageProcessing_imageProcess_0_0} -quiet] -quiet

# IP: bd/imageProcessing/ip/imageProcessing_axi_dma_0_0/imageProcessing_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessing_axi_dma_0_0 || ORIG_REF_NAME==imageProcessing_axi_dma_0_0} -quiet] -quiet

# IP: bd/imageProcessing/ip/imageProcessing_ps7_0_axi_periph_0/imageProcessing_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessing_ps7_0_axi_periph_0 || ORIG_REF_NAME==imageProcessing_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/imageProcessing/ip/imageProcessing_rst_ps7_0_50M_0/imageProcessing_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessing_rst_ps7_0_50M_0 || ORIG_REF_NAME==imageProcessing_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/imageProcessing/ip/imageProcessing_axis_dwidth_converter_0_0/imageProcessing_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessing_axis_dwidth_converter_0_0 || ORIG_REF_NAME==imageProcessing_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/imageProcessing/ip/imageProcessing_axi_smc_0/imageProcessing_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessing_axi_smc_0 || ORIG_REF_NAME==imageProcessing_axi_smc_0} -quiet] -quiet

# IP: bd/imageProcessing/ip/imageProcessing_xlconcat_0_0/imageProcessing_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessing_xlconcat_0_0 || ORIG_REF_NAME==imageProcessing_xlconcat_0_0} -quiet] -quiet

# IP: bd/imageProcessing/ip/imageProcessing_system_ila_0_0/imageProcessing_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessing_system_ila_0_0 || ORIG_REF_NAME==imageProcessing_system_ila_0_0} -quiet] -quiet

# IP: bd/imageProcessing/ip/imageProcessing_auto_pc_0/imageProcessing_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageProcessing_auto_pc_0 || ORIG_REF_NAME==imageProcessing_auto_pc_0} -quiet] -quiet

# XDC: bd/imageProcessing/imageProcessing_ooc.xdc
