# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_imageProcess_0_0/imageProcessing_imageProcess_0_0.xci
# IP: The module: 'imageProcessing_imageProcess_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_imageProcess_0_0/image_processing.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_imageProcess_0_0/image_processing.srcs/sources_1/ip/outputBuffer/outputBuffer.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_imageProcess_0_0/imageProcessing_imageProcess_0_0.xci
# IP: The module: 'imageProcessing_imageProcess_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_imageProcess_0_0/image_processing.srcs/sources_1/ip/outputBuffer/outputBuffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_imageProcess_0_0/image_processing.srcs/sources_1/ip/outputBuffer/outputBuffer.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
