# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/imageProcessing_system_ila_0_0.xci
# IP: The module: 'imageProcessing_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/bd_a9ac.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a9ac || ORIG_REF_NAME==bd_a9ac} -quiet] -quiet

# IP: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/ip/ip_0/bd_a9ac_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a9ac_ila_lib_0 || ORIG_REF_NAME==bd_a9ac_ila_lib_0} -quiet] -quiet

# IP: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/ip/ip_1/bd_a9ac_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a9ac_g_inst_0 || ORIG_REF_NAME==bd_a9ac_g_inst_0} -quiet] -quiet

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a9ac_ila_lib_0 || ORIG_REF_NAME==bd_a9ac_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a9ac_ila_lib_0 || ORIG_REF_NAME==bd_a9ac_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/ip/ip_0/bd_a9ac_ila_lib_0_ooc.xdc

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/bd_a9ac_ooc.xdc

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/imageProcessing_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessing_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/imageProcessing_system_ila_0_0.xci
# IP: The module: 'imageProcessing_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/bd_a9ac.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a9ac || ORIG_REF_NAME==bd_a9ac} -quiet] -quiet

# IP: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/ip/ip_0/bd_a9ac_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a9ac_ila_lib_0 || ORIG_REF_NAME==bd_a9ac_ila_lib_0} -quiet] -quiet

# IP: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/ip/ip_1/bd_a9ac_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a9ac_g_inst_0 || ORIG_REF_NAME==bd_a9ac_g_inst_0} -quiet] -quiet

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a9ac_ila_lib_0 || ORIG_REF_NAME==bd_a9ac_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a9ac_ila_lib_0 || ORIG_REF_NAME==bd_a9ac_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/ip/ip_0/bd_a9ac_ila_lib_0_ooc.xdc

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/bd_0/bd_a9ac_ooc.xdc

# XDC: c:/zyboz720/imageProcessing_PS/imageProcessing_PS.srcs/sources_1/bd/imageProcessing/ip/imageProcessing_system_ila_0_0/imageProcessing_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imageProcessing_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
